name: wedding_website
description: Site de mariage pour Joanne et Pierre
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Mise à jour de go_router pour bénéficier des API récentes (GoRouterState)
  go_router: ^13.2.0
  google_fonts: ^6.0.0
  lucide_icons: ^0.257.0
  url_launcher: ^6.2.6
  # Ajout du support de localisation et du package Intl pour la traduction
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
